Nama : Raveena Ayu Desember Suryoputri
NPM : 24083010028
Mata Kuliah : Matematika Diskrit A

In [37]:
import pandas as pd
import numpy as np
from numpy.linalg import norm

# 1. Membaca Data Excel
file_path = "Data Matdis pina.xlsx"
df = pd.read_excel(file_path)

# 2. Mengambil kolom C–F sebagai kriteria
C = df.iloc[:, 2:6]

# --- Perbaikan data ---
# Isi NaN dengan mean per kolom
C = C.fillna(C.mean())

# Menghapus kolom konstan agar korelasi tidak NaN
C = C.loc[:, C.nunique() > 1]

# Menyimpan ke dataframe bersih
df_clean = df.copy()
df_clean[C.columns] = C

# Ubah ke numpy array
C = C.to_numpy()

# 3. Tentukan bobot prioritas (matrix P)
P = np.array([0.2, 0.3, 0.4, 0.4])
P = P[:C.shape[1]]  

# 4. Hitung skor total (C × P)
scores = C @ P
df_clean["Skor_Total"] = scores

# Ambil 4 mahasiswa terbaik
top4 = df_clean.nlargest(4, "Skor_Total")

print("Empat mahasiswa terbaik berdasarkan skor total:")
print(top4[["NAMA", "Skor_Total"]])

# 5. Matriks kovarians & korelasi antar kriteria
cov_mat = np.cov(C, rowvar=False)
corr_mat = np.corrcoef(C, rowvar=False)

print("\nMatriks Kovarians:")
print(cov_mat)

print("\nMatriks Korelasi:")
print(corr_mat)

# 6. Cosine similarity antar mahasiswa (handle pembagian 0)
norms = norm(C, axis=1)
norms[norms == 0] = 1e-10   
cosine_sim = (C @ C.T) / (norms[:, None] * norms)
cosine_df = pd.DataFrame(cosine_sim, index=df["NAMA"], columns=df["NAMA"])

print("\nCosine Similarity (5x5 pertama):")
print(cosine_df.iloc[:5, :5])

# 7. Simpan hasil analisis ke Excel baru
with pd.ExcelWriter("Hasil_Analisis.xlsx") as writer:
    df_clean.to_excel(writer, sheet_name="Skor Mahasiswa", index=False)
    pd.DataFrame(cov_mat).to_excel(writer, sheet_name="Kovarians", index=False)
    pd.DataFrame(corr_mat).to_excel(writer, sheet_name="Korelasi", index=False)
    cosine_df.to_excel(writer, sheet_name="CosineSimilarity")

Empat mahasiswa terbaik berdasarkan skor total:
                          NAMA  Skor_Total
12        AMELIA RIZQYNA PUTRI        1.28
37           YUNIAR RACHMAWATI        1.28
6        Mohammad Alimun Hakim        1.20
29  MUHAMMAD WILDAN SULTANSYAH        1.04

Matriks Kovarians:
[[0.01370151 0.00996713 0.00561473 0.00561473]
 [0.00996713 0.0086522  0.00610125 0.00610125]
 [0.00561473 0.00610125 0.00652202 0.00652202]
 [0.00561473 0.00610125 0.00652202 0.00652202]]

Matriks Korelasi:
[[1.         0.91542422 0.5939545  0.5939545 ]
 [0.91542422 1.         0.81220226 0.81220226]
 [0.5939545  0.81220226 1.         1.        ]
 [0.5939545  0.81220226 1.         1.        ]]

Cosine Similarity (5x5 pertama):
NAMA                     MADINA HEDY ALIFANTI  MARIA DWI KURNIASIH  \
NAMA                                                                 
MADINA HEDY ALIFANTI                 1.000000             1.000000   
MARIA DWI KURNIASIH                  1.000000             1.000000   
ADINDA

INTERPRETASI